version: "3.9"  # Or your preferred version

services:
  postgres:  # Service name for PostgreSQL
    image: postgres:latest  # Or a specific version (e.g., postgres:15)
    ports:
      - "5432:5432" # Only needed if you want to access from host, you can remove this
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orm_app_db
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data
  app:
    image: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA}
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/orm_app_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
volumes:
  db_data: # Named volume for database data